name: Actualizar Mapa de Avisos

on:
  schedule:
    - cron: "*/10 * * * *"  # Ejecuta cada 10 minutos
  workflow_dispatch:  # Permite ejecutarlo manualmente desde GitHub Actions

jobs:
  update-warnings:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: Ejecutar script de actualización
        run: python actualizar_warnings.py
        env:
          METEOBLUE_API_KEY: ${{ secrets.METEOBLUE_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Subir cambios al repositorio
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add warnings.geojson
          git commit -m "Actualizar avisos meteorológicos"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
