name: Actualizar Avisos MeteoBlue

on:
  schedule:
    - cron: "*/10 * * * *"  # Ejecutar cada 10 minutos
  workflow_dispatch:  # Permite ejecutarlo manualmente desde GitHub Actions

jobs:
  update_warnings:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Instalar dependencias
        run: pip install requests PyGithub

      - name: Ejecutar script de actualización
        env:
          METEOBLUE_API_KEY: ${{ secrets.METEOBLUE_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python actualizar_warnings.py

      - name: Configurar Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Subir cambios si hay modificaciones
        run: |
          git add warnings.geojson
          git commit -m "Actualizar avisos meteorológicos" || echo "No hay cambios para confirmar"
          git push
